/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.view;

import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 *
 * @author guilherme
 */
public class DixonResultPanel extends javax.swing.JPanel {

    /**
     * Creates new form DixonResultPanel
     */
    private DecimalFormat df = new DecimalFormat("####0.0000");

    public DixonResultPanel() {
        initComponents();
        resetFields();
    }

    public void resetFields() {
        labelResultResult.setText("---");
        labelResultLower.setText("0.0000");
        labelResultUpper.setText("0.0000");
        labelResultN.setText("0");
        labelResultRemoved.setText("---");
    }

    public String removedsToList(ArrayList<Double> removeds) {
        String text = "";

        if (removeds.isEmpty()) {
            text="---";
        } else {
            for (Double d : removeds) {
                text = text.concat(df.format(d) + "<br>");
            }
        }
        return text;
    }

    public void setAll(boolean approved, Double lower, Double upper, int n, ArrayList<Double> removed) {
        if (approved) {
            labelResultResult.setText("<html><div style='color:#008C07;'>Approved</div></html>");
            labelResultLower.setText(df.format(lower));
            labelResultUpper.setText(df.format(upper));
            labelResultN.setText("" + n);
            labelResultRemoved.setText("<html>" + removedsToList(removed) + "</html>");
        } else {
            resetFields();
            labelResultResult.setText("<html><div style='color:#E20705;'>Reproved</div></html>");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelResult = new javax.swing.JLabel();
        labelResultResult = new javax.swing.JLabel();
        labelLowerEnd = new javax.swing.JLabel();
        labelUpperEnd = new javax.swing.JLabel();
        labelN = new javax.swing.JLabel();
        labelRemovedValues = new javax.swing.JLabel();
        labelResultLower = new javax.swing.JLabel();
        labelResultN = new javax.swing.JLabel();
        labelResultUpper = new javax.swing.JLabel();
        labelResultRemoved = new javax.swing.JLabel();

        labelResult.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        labelResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelResult.setText("Result:");

        labelResultResult.setText("---");

        labelLowerEnd.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        labelLowerEnd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelLowerEnd.setText("Lower end:");

        labelUpperEnd.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        labelUpperEnd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUpperEnd.setText("Upper end:");

        labelN.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        labelN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelN.setText("N:");

        labelRemovedValues.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        labelRemovedValues.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelRemovedValues.setText("Removed values:");

        labelResultLower.setText("0.00");

        labelResultN.setText("0");

        labelResultUpper.setText("0.00");

        labelResultRemoved.setText("---");
        labelResultRemoved.setToolTipText("<text/html>");
        labelResultRemoved.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelRemovedValues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelUpperEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelResult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelLowerEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelResultResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelResultLower, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(labelResultUpper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelResultN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelResultRemoved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelLowerEnd, labelN, labelRemovedValues, labelResult, labelUpperEnd});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelResult)
                    .addComponent(labelResultResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLowerEnd)
                    .addComponent(labelResultLower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUpperEnd)
                    .addComponent(labelResultUpper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelN)
                    .addComponent(labelResultN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelRemovedValues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelResultRemoved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelLowerEnd;
    private javax.swing.JLabel labelN;
    private javax.swing.JLabel labelRemovedValues;
    private javax.swing.JLabel labelResult;
    private javax.swing.JLabel labelResultLower;
    private javax.swing.JLabel labelResultN;
    private javax.swing.JLabel labelResultRemoved;
    private javax.swing.JLabel labelResultResult;
    private javax.swing.JLabel labelResultUpper;
    private javax.swing.JLabel labelUpperEnd;
    // End of variables declaration//GEN-END:variables
}
