/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.view;

import java.awt.TextField;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JTextField;

/**
 *
 * @author guilherme
 */
public class DixonPanel extends javax.swing.JPanel {

    
    private BoxLayout boxLayout;
    private static int fields=0;
    
    /**
     * Creates new form DixonPanel
     */
    public DixonPanel() {
        initComponents();
        boxLayout=new BoxLayout(this,BoxLayout.PAGE_AXIS);
        createField();
    }

    private void createField(){
        fields++;
        add("valueField"+fields,new TextField("0.00"));
    }
    
    private void removeField(int index){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setLayout(null);

        jButton1.setText("Ok");
        add(jButton1);
        jButton1.setBounds(472, 300, 90, 30);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
